# Generated by Django 5.0.7 on 2024-08-12 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ("name",),
                "verbose_name": "ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredientinrecipe",
            options={
                "ordering": ("ingredient",),
                "verbose_name": "ингредиент в рецепте",
                "verbose_name_plural": "Ингредиенты в рецептах",
            },
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="Количество игредиентов не может быть меньше1.",
                    ),
                    django.core.validators.MaxValueValidator(
                        32000,
                        message="Количество игредиентов не может быть больше 32000.",
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
    ]
