# Generated by Django 5.0.7 on 2024-08-12 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcartingredients",
            options={
                "ordering": ("recipe",),
                "verbose_name": "рецепт в списке покупок",
                "verbose_name_plural": "Рецепты в списке покупок",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="Время приготовления не может быть менее 1 минуты.",
                    ),
                    django.core.validators.MaxValueValidator(
                        2880,
                        message="Время приготовления не может быть более 48.0 часов.",
                    ),
                ],
                verbose_name="Время приготовления, мин",
            ),
        ),
    ]
