# Generated by Django 5.0.7 on 2024-08-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
