name: Main Foodgram workflow

on:
  pull_request:
    branches:
      - main

jobs:
  backend_tests:
    name: Backend flake8 tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r ./backend/requirements.txt 

    - name: Flake8 test
      run: |
        python -m flake8 backend/